apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: artifactory-artifact-collector
  name: artifactory-artifact-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: artifactory-artifact-collector
    spec:
      containers:
      - image: hygieia-artifactory-artifact-collector
        name: artifactory-artifact-collector
        resources: {}
      restartPolicy: Always
status: {}
